name: Whitelion
favicon: null
layout_spectrum: 0.98803
typography_spectrum: 0.22205663844943047
title: White Lion Detail
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e0e'
    - '#e7e7e7'
    - '#159bdc'
    - '#dc1a83'
    - '#e37c22'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 1
purpose: []
