name: 'White Lion Dip & Detail'
favicon: null
layout_spectrum: 0.47563
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c10'
    - '#b71021'
    - '#3686cf'
    - '#ca2948'
    - '#172741'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
