name: Whitelion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49335
title: White Lion Detail
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e0e'
    - '#e7e7e7'
    - '#159bdc'
    - '#dc1a83'
    - '#e37c22'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
