name: 'White Lion Dip & Detail'
favicon: null
layout_spectrum: 0.49549
typography_spectrum: 0.49188
title: 'White Lion Dip & Detail'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c10'
    - '#b71021'
    - '#3686cf'
    - '#ca2948'
    - '#172741'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
