name: 'White Lion Dip & Detail'
favicon: null
layout_spectrum: 0.73736
typography_spectrum: 1
title: 'White Lion Dip & Detail'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c10'
    - '#b71021'
    - '#3686cf'
    - '#ca2948'
    - '#172741'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
