name: Whitelion
favicon: null
layout_spectrum: 0.16659721452742815
typography_spectrum: 0.22205663844943047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffeff'
    - '#313131'
    - '#ababab'
    - '#838383'
  brandStrength: 0.49116470222361386
  lightness: 0.8440788520965725
  saturation: 0.8359914091415703
  rhythmicContrast: 0.1577514661476016
purpose: []
