name: Whitelion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49335
title: White Lion Detail
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c10'
    - '#b71021'
    - '#3686cf'
    - '#ca2948'
    - '#172741'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
