analytics: {}
color:
  brandColors:
    - '#0b0c10'
    - '#b71021'
    - '#3686cf'
    - '#ca2948'
    - '#172741'
  brandStrength: 0.0625
  lightness: 0.5625
  rhythmicContrast: 0
  saturation: 0.5
cta: {}
layout_spectrum: 0.804054
name: Whitelion
opengraph: {}
purpose: []
typography_spectrum: 1
